tracker: CSRT
tau: 0.3
resize_factor: 1

out_players: output/Tracking/tracked_players.avi
out_players_mask: output/Tracking/tracked_players_mask.avi
out_homography: output/Tracking/tracked_homography.avi
out_bboxes: output/Tracking/bounding_box.png
out_players_data: output/Tracking/data_players.txt
out_tracking_results: output/Tracking/results.png
input_image_homography: sources/Map/basket_field.jpg

masker: SemiSupervised
custom_trackers: [SemiSupervisedTracker, LinPuntracker] #trackers for which we haven't implemented a full compatible structure with OpenCV's trackers
update_mask: False
