# Parameters used by benchmark.py
# See 'config.yaml' for more details on the meaning of each param

tracker: CSRT
tau: 0.3
resize_factor: 1

show_novelty_detection: False
show_masks: False
show_homography: False
debug: False

out_players: output/Tracking/tracked_players.avi
out_players_mask: output/Tracking/tracked_players_mask.avi
out_homography: output/Tracking/tracked_homography.avi
out_bboxes: output/Tracking/bounding_box.png
out_players_data: output/Tracking/data_players.txt
out_tracking_results: output/Tracking/results.png
input_image_homography: sources/Map/basket_field.jpg

masker: SemiSupervised
custom_trackers: [SemiSupervisedTracker, LinPuntracker] 
update_mask: False

manual_roi_selection: False
multi_selection: True
re_init_span: 3
