# Parameters used by benchmark.py
# See 'config.yaml' for more details on the meaning of each param

tracker: CSRT
resize_factor: 1

show_novelty_detection: False
show_masks: False
debug: False

masker: SemiSupervised
custom_trackers: [SemiSupervisedTracker, LinPuntracker] 
update_mask: False

manual_roi_selection: False
multi_selection: True
re_init_span: 3
