tracker: CSRT # Rigid tracker method
resize_factor: 1 # Resize factor (betwwen 0 and 1) to use on the video input. With a value of 1, the algorithm is run on the full-size video. Otherwise, the input video is scaled down.

show_novelty_detection: False # If True show the novelty detection results
show_masks: True # If True shows the resulting binary mask as the algorithm computes it
debug: True # If True show debug mesages and export resulting masks. Should always be True, is set to False only when running benchmark.py

out_tracked: Output/tracked.avi # Where to save the resulting video with tracking information
out_binary_mask: Output/binary_mask.avi # Where to save the resulting binary mask
out_mask: Output/mask.avi # Where to save the resulting mask (the mask is shown as a red overlay over the input video)

input_video: Input/SegTrack2/Video/soldier.mp4 # Input video
input_truth: Input/SegTrack2/Truth/soldier.mp4 # Binary truth mask of the correct segmentation. Can be null if not available

masker: PC # Masker id
custom_trackers: [LinPuntracker] # Trackers for which we haven't implemented a full compatible structure with OpenCV's trackers
update_mask: False

manual_roi_selection: False # Enable manual polygon (ROI) selection. If False, the polygons specified in the 'pts' parameters are used
multi_selection: True # Enable the selection of multiple frames to train the models. Used in PixelClassification algorithm
re_init_span: 3  # Define new ROI/RONI every tot_duration_clip/re_init_span, first selection excluded

# Hyperparameters used by the masker. Currently supprted only by the SupervisedLearning masker
params:
  n_estimators: 20
  max_depth: 5
  n_components: 1
  novelty_detection: False
  over_segmentation: quickshift
  features: "8 hsv_lab"
  dilation_kernel: 7
  prior_weight: 0.0

# Polygons selections for for soldier.mp4, see 'polugons.yaml' for other configurations.
pts: [[[[419, 16], [427, 22], [430, 33], [423, 46], [425, 66], [432, 81], [444, 120], [435, 112], [414, 114], [417, 143], [419, 157], [410, 180], [420, 205], [411, 212], [397, 206], [403, 158], [390, 152], [387, 169], [374, 178], [360, 191], [354, 213], [346, 202], [348, 178], [375, 160], [367, 136], [365, 104], [346, 101], [367, 79], [390, 50], [404, 33], [408, 22]], [[409, 33], [420, 42], [417, 54], [440, 112], [425, 104], [409, 109], [410, 119], [424, 138], [416, 174], [415, 196], [398, 194], [411, 148], [388, 140], [383, 211], [370, 206], [378, 160], [362, 122], [363, 91], [378, 79], [393, 55], [399, 38]], [[400, 56], [411, 60], [407, 69], [409, 86], [412, 100], [411, 113], [399, 112], [397, 132], [408, 155], [404, 173], [396, 194], [380, 193], [376, 178], [385, 174], [385, 155], [376, 142], [366, 123], [365, 105], [381, 83], [393, 66]], [[395, 73], [402, 81], [404, 100], [408, 119], [394, 123], [404, 152], [403, 167], [393, 204], [389, 197], [393, 174], [383, 157], [369, 142], [368, 119], [373, 104], [385, 84]]]]
pts_frame_numbers: [0, 10, 20, 30]
bboxes_roni: [[[455, 23, 28, 127], [461, 69, 25, 94], [344, 25, 33, 62], [335, 31, 37, 66]]] # Remember to translate tuples into list. Comment field to manually select RONI

